# Generated by Django 4.2.4 on 2023-08-29 19:11

from django.db import migrations
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='NY', max_length=2),
        ),
    ]
